version: '3'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=nekocat
      - POSTGRES_PASSWORD=nekocat
      - POSTGRES_DB=nekocat
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data/base.sql:/docker-entrypoint-initdb.d/base.sql
      - ./data/insert.sql:/docker-entrypoint-initdb.d/insert.sql
    networks:
      - app-network
    ports:
      - '5432:5432'
    restart: always

  app:
    depends_on:
      - postgres
    container_name: nekocat
    build:
      context: .
      dockerfile: Dockerfile
    image: nekocat:v1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/nekocat
      - SPRING_DATASOURCE_USER=nekocat
      - SPRING_DATASOURCE_PASSWORD=nekocat
    ports:
      - '8080:8080'
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
